FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go vet ./... && go test ./... -count=1

EXPOSE 8081

CMD ["go", "run", "./cmd/bot/"]
